[build.environment]
GO_VERSION = "1.24.0"
HUGO_VERSION = "0.144.2"
NODE_VERSION = "22"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = """\

  # Install Tailwind and plugins
  echo "Installing Tailwind CSS and plugins..." && \
  npm install tailwindcss@^3.3.0 && \
  npm install -D @tailwindcss/typography && \
  npm install -D @tailwindcss/forms && \
  npm install -D @tailwindcss/aspect-ratio && \
  npm install -D @tailwindcss/container-queries && \

  # Output Node version
  echo "USING NODE VERSION: $(node -v)" && \
  
  # Install Go
  echo "Installing Go $GO_VERSION..." && \
  curl -sSOL https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
  export PATH=$PATH:/usr/local/go/bin && \
  rm -rf go${GO_VERSION}.linux-amd64.tar.gz && \
  go version && \
  
  # Install Hugo
  echo "Installing Hugo $HUGO_VERSION..." && \
  curl -sSOL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz && \
  tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz && \
  mv hugo /usr/local/bin/ && \
  rm -rf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz && \
  hugo version && \
  
    
  # Project setup
  echo "Project setting up..." && \
  npm run project-setup && \
  
  # Install dependencies
  echo "Installing project dependencies..." && \
  npm install && \
  
  # Build the project
  echo "Running the build command..." && \
  npm run build \
  """